### ISSUE TITLE
Issues on methylation results interpretation

### ISSUE THREAD

**Issue by PanZiwei** [nanoporetech/fast5mod#10]
Hi,
Thank you so much for the amazing tool. I have successfully used fast5mod to call modifications from Guppy result, but I have several questions about the output interpretation and would really appreciate it if you can help to answer them below:

Here is an example result for what I got(I added the header manually):
```
chr    position motif fwd.meth.count rev.meth.count fwd.canon.count rev.canon.count
chr10	10493	 CG	    0	        0	            0	    0
chr10	10496	 CG	    1	        0	            0	    0 
chr10	10507	 CG	    0	        0	            0	    0
```
1. The result is per-site level instead of per-read level right? Is it possible to generate per-read level results?
2. The methylation frequency = (fwd.meth.count + rev.meth.count) / (fwd.meth.count + rev.meth.count + fwd.canon.count + rev.canon.count)? For example, at chr10 10496, the methylation frequency = 1 / 1 = 100%?  How about the undertermined reads? 
3. The result is 0-based or 1-based?
4. You mentioned that "the position field records the position of the first base in the motif recorded.", so in the CpG case, it should indicate the C position? There will be 1 base shift for forwarding sequence and reverse sequence(e.g. In the forward sequence is CpG, but in the reversed it should be GpC), how do you deal with the issue? Is it possible to add the strand information?

Thank you so much for your help!

**Comment by cjw85** [comment]
Hi @PanZiwei,

Thank you for your questions.

1. Correct the results are per-site, and the numbers in the four final columns are the counts of confidently determined reads. The per-read values can be recovered from the bam file, this is really just a transcription from the original Guppy files but stored in the BAM for convenience so the data is more easily accessed during the pileup processing.
2. The undetermine/unconfident calls are not recorded in this tabular output.
3. IIRC the results a 0-based
4. The co-ordinate is with respect to the forward orientation of the reference. As you indicate the position on the second strand is not the same, the table already takes to this into account and the "rev" counts are for e.g. 1-base shifted for CpG.

**Comment by PanZiwei** [comment]
@cjw85 
Thank you for your quick response.
Following the Q4, if I want to use the position to indicate the modified base location with the forward orientation of the reference, do you think it will more sense to separate forward and reversed strand based on current result since the modification location is different? 
For example, the 2nd row actually means that chr10 10496 is for C in CpG in the forward strand, and chr10 10497 is for C in CpG in reversed strand? (i.e. G in CpG in the forward strand)? 
It will be something like:
```
chr    position strand motif fwd.meth.count fwd.canon.count
chr10	10496	+        CG	    1	        0	
chr    position strand motif rev.meth.count rev.canon.count            
chr10	10497	-         CG	    0	        0	  
```

**Comment by cjw85** [comment]
That would be a correct interpretation of the data from the original table.

**Comment by PanZiwei** [comment]
Hi @cjw85 ,
One more question on the per-read level information extraction. Do you have any suggestions to deal with the bam file? Maybe I should have a look at pysam pacakge?
Thank you so much for your help!

**Comment by PanZiwei** [comment]
Hi @cjw85 ,
One more question on the per-read level information extraction. Do you have any suggestions/directions to deal with the bam file? Maybe I should have a look at pysam package?

I have a look at [your code block](https://github.com/nanoporetech/fast5mod/blob/60b16f7da986c3629ee5605c506635a15a0d5078/fast5mod/programs.py#L114-L157) but I am not sure where you store the modification base score in the bam file...

```
samtools view -h  test.chr10.bam | head -8
@HD	VN:1.5	SO:coordinate
@CO	Guppy basecaller mod. base tags are stored w.r.t. the sequencing direction, they should be reversed for reads aligning to the reverse strand.
@SQ	SN:chr1	LN:248956422
@SQ	SN:chr2	LN:242193529
@SQ	SN:chr3	LN:198295559
@SQ	SN:chr4	LN:190214555
@SQ	SN:chr5	LN:181538259
@SQ	SN:chr6	LN:170805979
```

Thank you so much for your help!

**Comment by cjw85** [comment]
You should look in the call methylation function of that file which shows how the pileup API in pysam can be used to extract the base and methylation status of reads at a given genomic position.
