### ISSUE TITLE
score for upper (lower) boundary filtering to call methylated base

### ISSUE THREAD

**Issue by yemingx** [nanoporetech/fast5mod#6]
Hi, would you please kindly explain what is the meaning of the filtering score in the "--filter" parameter of the fast5mod call? How this score is generated? And why the default --filter setting is (64, 128)?

  --filter upper lower  Upper (lower) score boundary to call canonical
                        (methylated) base. Scores are in the range [0, 256].
                        (default: (64, 128))

If I interpreted correctly, this score was generated from ModBaseProbs in the hdf5 of the Guppy Dcm, Dam, and CpG methylation calling output. 

The meaning of the ModBaseProbs is explained as written below according to their Modified base calling documents:

"""
Each table row describes the likelihood that, given that a particular base was called at that position, that base is either a canonical one (i.e. a base that the model considers to be "unmodified"), or one of the modifications that is contained within the model. The contents of the table are integers in the range of 0-255, which represent likelihoods in the range of 0-100% (storing these values as integers allows us to reduce .fast5 file size). For example, a likelihood of 100% corresponds to a table entry of 255. Within a given row the table entries for a particular base will sum to 100%.

Following from our previous example with 6mA and 5mC, you might see a table row with entries like this:

[63, 192, 255, 0, 255, 255]

This would mean that:

Given that an A was called, the likelihood that it is a canonical A is ~25% (63 / 255), and the likelihood that it is 6mA is ~75% (192 / 255).
Given that a C was called, the likelihood that it is a canonical C is 100% (255 / 255), with no chance (0 / 255) of it being a 5mC.
Given that a G or T was called, the likelihood that they are canonical bases is 100% (255 / 255 -- this should always be the case, as the model does not include any modification states for G or T).
"""

**Comment by cjw85** [comment]
Low per-read modified base scores indicate that the position is not a modified base; high scores indicate that the position is modified. To produce a decisive per-read prediction the scores are thresholded into three categories: canonical, undetermined, and modified. The two filter values determine the boundary scores for these classes.

**Comment by yemingx** [comment]
Hi, cjw85. Thanks for your timely response! The information is quite helpful.

**Comment by PanZiwei** [comment]
Hi @cjw85 
following the questions, do you mean that:
If the modified base scores 0 <= S < 64, it is canoncial; if 64 <= S <= 128, it is undertermined; If 128 < S <= 256, it is modfified?

**Comment by cjw85** [comment]
Correct
