### ISSUE TITLE
Getting "Processed 0 ref positions (0%)" for final tsv output

### ISSUE THREAD

**Issue by dipannita-g** [nanoporetech/fast5mod#7]
Hi!
For the final tab delimited file, when I use the following, my output gives 0 value for all positions.
>BAM=meth.bam
>REFERENCE=MRSA.fasta
>REGION=7e24d142adc2427d_1:1-50000
>OUTPUT=meth.tsv
>fast5mod call --meth all ${BAM} ${REFERENCE} ${REGION} ${OUTPUT}

It says  **Processed 0 ref positions (0%)** for all the bases A, C, T and G. 
I am assuming there is something wrong with my "Region" or "Reference" input.
I'll greatly appreciate any help to troubleshoot this!

**Comment by cjw85** [comment]
Hi @dipannita-g,

Apologies for the lack of response here. If you have not already resolved this, I believe you will need to put quotes around `${REGION}` for the command to be interpreted correctly by the shell. You could simply do:

    fast5mod call --meth all meth.bam MRSA.fasta 7e24d142adc2427d_1:1-50000 meth.tsv
